"""Generate the portable, read-only guide from the package's Markdown topics."""
import argparse
import json
from pathlib import Path
import pymicroglia
from pymicroglia import context


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    root=Path(__file__).resolve().parents[1]
    bundle={'schema_version':1,'package':'pymicroglia','distribution':'PyMicroglia',
            'version':pymicroglia.__version__,
            'reader':{'purpose':'Read-only package usage orientation',
                      'python':"from pymicroglia import context; context.read(format='json')",
                      'topic':"context.read('measure', format='json')",
                      'search':"context.search('period search range')"},
            'topics':[context.read(topic,format='json') for topic in context.topics()]}
    outputs={root/'src/pymicroglia/pymicroglia_context.json':json.dumps(bundle,indent=2,ensure_ascii=False)+'\n',
             root/'README_AI.md':'<!-- Generated by scripts/generate_agent_context.py. -->\n\n'+'\n\n'.join(row['content'].rstrip() for row in bundle['topics'])+'\n'}
    stale=[]
    for path,text in outputs.items():
        if not path.exists() or path.read_text(encoding='utf-8')!=text:
            stale.append(str(path.relative_to(root)))
            if not args.check:path.write_text(text,encoding='utf-8')
    if args.check and stale:raise SystemExit('Stale guide: '+', '.join(stale))


if __name__=='__main__':main()
